name: Assign Issue Number

on:
  workflow_call:
    secrets:
      app_id:
        required: true
      app_key:
        required: true

jobs:
  assign-issue-number:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set issue prefix # Current year // Y24, Y25 etc
        run: echo "ISSUE_PREFIX=Y$(date +'%y')" >> $GITHUB_ENV

      - name: Get token
        id: get_workflow_token # Generates a token for the action
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.app_id }}
          application_private_key: ${{ secrets.app_key }}

      # Updates org variable for the counter & updates the issue title
      - name: Assign custom issue number
        uses: sanger/issuer@main
        with:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          ISSUE_PREFIX: ${{ env.ISSUE_PREFIX }}
          ISSUE_COUNTER_VAR: "ISSUE_NUMBER"
          ORG_NAME: "sanger"
