name: Assign Issue Number

on:
  issues:
    types: [opened]

jobs:
  call-add-to-project:
    uses: sanger/issuer/.github/workflows/generate_issue_number.yml@develop
    secrets:
      app_id: ${{ secrets.ISSUE_GEN_APP_ID }}
      app_key: ${{ secrets.ISSUE_GEN_APP_KEY }}
